[package]
name = "ai-automation-workflow-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
pretty_env_logger = "0.5"
log = "0.4"
serde = {version = "1" , features = ["derive"]}
serde_json = "1"